# Site settings
title: "Retro64.xyz"
# email:
description: > # this means to ignore newlines until "baseurl:"
    Old technology is some of the best technology. This is where all the things
    that I want to reminisce about live. I provide high quality and impactful
    training on a wide range of topics. Sometimes I blog, vlog, and just speak
    my mind. 
url: "http://localhost:4488"
twitter_username: Retro64XYZ
github_username: Retro64XYZ
mastodon_username: Retro64XYZ
keybase_username: Retro64XYZ
#email_display: Retro64XYZ
#email_sendto: example@example.com
youtube_display: Retro64XYZ
youtube_username: 'channel/UC8dI8JKzbheHlaGhUGxIV1w?disable_polymer=true'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
port: 4488
permalink: pretty
post_ext: md
keep_files: [assets]
# Pagination Settings
paginate: 5
paginate_path: "/index/page:num"
# Search Rules
lunr_search:
  js_dir: "js"
# Gems
plugins:
  - jekyll-paginate
  - jekyll-lunr-js-search
